config/routes.rb
Rails.application.routes.draw do
  root to: 'maps#index'
  resources :maps, only: [:index]
  get 'search', to: "search#search"
  get '/map_request', to: 'maps#map', as: 'map_request'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end

  def map
    results = Geocoder.search(params[:address])
    @latlng = results.first.coordinates
    # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。
    
    # respond_to以下の記述によって、
    # remote: trueのアクセスに対して、
    # map.js.erbが変えるようになります。
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    if postal_code = params[:postal_code]
      params = URI.encode_www_form({zipcode: postal_code})
      uri = URI.parse("http://zipcloud.ibsnet.co.jp/api/search?#{params}")
      response = Net::HTTP.get_response(uri)
      result = JSON.parse(response.body)
      if result["results"]
        @zipcode = result["results"][0]["zipcode"]
        @address1 = result["results"][0]["address1"]
        @address2 = result["results"][0]["address2"]
        @address3 = result["results"][0]["address3"]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostalCodeSearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= form_with url: search_path, method: :get, local: true do |f| %>
        <%= f.text_field :postal_code, class: "search_form", placeholder: "郵便番号を入力してください" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/maps/index.html.erb
<h2>gmap</h2>
<%= form_with url: map_request_path, method: :get do |f|%>
  <%= f.text_field :address %>
  <%= f.submit '地図表示' %>
<% end %>

<div id="map">
</div>

<style>
#map{
  height: 400px;
}
</style>

<script>
  let mapInstance

  function initMap(){
    mapInstance = new google.maps.Map(document.getElementById('map'), {
    center: {lat: -34.397, lng: 150.644},
    zoom: 8
    });
  }


</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVUrrIPBR_xl1xlCeAmYCWPR6-SG2MLQA&callback=initMap" async defer></script>

app/views/maps/map.js.erb
/* 
index.html.erbのscript内に
google mapのインスタンス変数である、
mapという変数があることに留意
*/

(function(){
  // 位置情報をもつ変数を用意
  let pos = new google.maps.LatLng(
   <%= @latlng[0] %>, //latitude
   <%= @latlng[1] %>  //longitude
  );

  mapInstance.setCenter(pos)
  let marker = new google.maps.Marker({
    map: mapInstance,
    position: pos
  });
})()

app/views/search/search.html.erb
<p>
  郵便番号：<%= @zipcode %>
</p>
<p>
  都道府県：<%= @address1 %>
</p>
<p>
  市区町村：<%= @address2 %>
</p>
<p>
  町域：<%= @address3 %>
</p>